services:
  - type: web
    name: ai-first-crm-hcp
    runtime: docker
    plan: free
    region: ohio
    envVars:
      - key: GROQ_API_KEY
        value: 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
      - key: GROQ_PRIMARY_MODEL
        value: openai/gpt-oss-20b
      - key: GROQ_CONTEXT_MODEL
        value: openai/gpt-oss-120b
      - key: DATABASE_URL
        sync: false
      - key: APP_ENV
        value: production
